consul-exporter:
  hostname: consul-exporter
  container_name: consul-exporter
  net: ${NETWORK}
  image: prom/consul-exporter
  command: -consul.server=${CONSUL_SERVER}
  environment:
   - constraint:node==${NODE_2}
  ports:
    - "9107:9107"
